name: Build app and Deploy to GKE

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: nino-cluster-1
  CLUSTER_ZONE: us-central1-a
  GKE_VERSION: 1.32.0
  GKE_DEPLOYMENT_NAME: nino-db
  GKE_DEPLOYMENT_NAMESPACE: default
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nino-db:${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_TF_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
          gcloud auth configure-docker -q
      
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push $IMAGE_NAME

      # - name: Set up Kubernetes credentials
      #   run: |
      #     gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

      # - name: Deploy to GKE
      #   run: |
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl apply -f k8s/service.yaml
      #     kubectl apply -f k8s/ingress.yaml
