name: Build app and Deploy to GKE

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: nino-cluster-1
  CLUSTER_ZONE: us-central1-a
  GKE_VERSION: 1.32.0
  GKE_DEPLOYMENT_NAME: nino-db
  GKE_DEPLOYMENT_NAMESPACE: default
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nino-db:latest

jobs:
  build_and_push_gcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_TF_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
          gcloud auth configure-docker -q
      
      - name: Build and Push Docker image to Google Container Registry
        run: |
          cd App
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Get Kubernetes credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

      - name: Installing Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to GKE with Helm
        run: |
          cd Charts/ninodb
          helm upgrade --install nino-db ./charts/nino-db \
            --namespace default \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=latest \
            --set ingress.enabled=true
            --set gcrSA-Key="${{ secrets.GH_TF_KEY }}"