name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GH_TF_KEY }}
  CLUSTER_NAME: nino-cluster-1
  CLUSTER_ZONE: us-central1-a
  GKE_VERSION: 1.32.0
  GKE_DEPLOYMENT_NAME: nino-db
  GKE_DEPLOYMENT_NAMESPACE: default
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nino-db:${{ github.sha }}

jobs:
  Infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2" 

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_GCS_BACKEND_NAME }}" \
            -backend-config="prefix=state/terraform.tfstate" 

      - name: Run Terraform Plan
        run: | 
          terraform plan -input=false -out=tfplan\
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}"

      - name: Run Terraform Apply
        run: |
          terraform apply -input=false -auto-approve tfplan

  Build_and_Deploy_app:
    needs: Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_TF_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
          gcloud auth configure-docker -q
      
      - name: Build and Push Docker image to Google Container Registry
        run: |
          cd App
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
  
      - name: 'Install gke-gcloud-auth-plugin'
        run: |
          gcloud components install gke-gcloud-auth-plugin -q
          gcloud components update -q

      - name: Get Kubernetes credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GOOGLE_PROJECT

      - name: Installing Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Test Helm Command Variations
        run: |
          helm upgrade --install nino-db Charts/nino-db --dry-run --debug || echo "Failed: Debug mode"

#      - name: Deploy to GKE with Helm
#        run: |
#          echo "Current directory: $(pwd)"
#          helm version
#          helm upgrade --install "nino-db" "Charts/nino-db" --dry-run --debug --namespace $GKE_DEPLOYMENT_NAMESPACE \
#          --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nino-db \
#          --set image.tag=${{ github.sha }} \
#          --set ingress.enabled=true \
#          --set gcrSAKey="${{ secrets.GH_TF_KEY }}" \
#          --wait