name: Build, Plan, Apply Terraform, and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GH_TF_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2" 

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_GCS_BACKEND_NAME }}" \
            -backend-config="prefix=state/terraform.tfstate" 

      - name: Run Terraform Plan
        run: | 
          terraform plan -input=false -out=tfplan\
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}"

      - name: Run Terraform Apply
        run: |
          terraform apply -input=false -auto-approve tfplan